FROM oven/bun:1.3.11
WORKDIR /app

COPY package.json bun.lock ./
COPY apps/api/package.json apps/api/
COPY apps/web/package.json apps/web/
COPY apps/dns-server/package.json apps/dns-server/
RUN BUN_FROZEN_LOCKFILE=0 bun install --production

COPY apps/api apps/api

ENV NODE_ENV=production
ENV PORT=8080
EXPOSE 8080

CMD ["bun", "apps/api/src/index.ts"]
